services:
  # ------------------------------------
  # 1. Auth Service Database
  # ------------------------------------
  auth-db:
    image: postgres:15-alpine
    container_name: aim_auth_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ------------------------------------
  # 2. Auth Service (Go App)
  # ------------------------------------
  auth-service:
    build:
      context: ./auth-service 
      dockerfile: Dockerfile
    container_name: aim_auth_service
    ports:
      - "8080:8080"
    environment:
      DB_HOST: auth-db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: auth_db
      DB_PORT: 5432
      JWT_SECRET: "my_super_secret_key_123"
    depends_on:
      auth-db:
        condition: service_healthy

  # ------------------------------------
  # 3. Account Service Database
  # ------------------------------------
  account-db:
    image: postgres:15-alpine
    container_name: aim_account_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: account_db
    ports:
      - "5433:5432" 
    volumes:
      - account_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d account_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ------------------------------------
  # 4. Account Service (Go App)
  # ------------------------------------
  account-service:
    restart: on-failure
    build:
      context: ./account-service
      dockerfile: Dockerfile
    container_name: aim_account_service
    ports:
      - "8081:8081" 
    environment:
      DB_HOST: account-db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: account_db
      DB_PORT: 5432
      JWT_SECRET: "my_super_secret_key_123" 
    depends_on:
      account-db:
        condition: service_healthy

# 5. Transaction Service Database
  transaction-db:
    image: postgres:15-alpine
    container_name: aim_transaction_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transaction_db
    ports:
      - "5434:5432" 
    volumes:
      - transaction_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d transaction_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 6. Transaction Service
  transaction-service:
    restart: on-failure
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    container_name: aim_transaction_service
    ports:
      - "8082:8080" # inside 8080 outside 8082
    environment:
      DB_HOST: transaction-db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: transaction_db
      DB_PORT: 5432
      JWT_SECRET: "my_super_secret_key_123"
      ACCOUNT_SERVICE_URL: "aim_account_service:50051" 
      RABBITMQ_URL: "amqp://user:password@rabbitmq:5672/"
    depends_on:
      transaction-db:
        condition: service_healthy
      account-service: 
        condition: service_started
      rabbitmq:
        condition: service_healthy

# 7. RabbitMQ (Message Broker)
  rabbitmq:
    image: rabbitmq:3-management-alpine 
    container_name: aim_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default 

# ------------------------------------
# Volumes Definition 
# ------------------------------------
volumes:
  auth_db_data:
  account_db_data:
  transaction_db_data: